/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCategoria;
import controller.ControllerFornecedor;
import controller.ControllerProduto;
import java.sql.Date;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCategoria;
import model.ModelFornecedor;
import model.ModelProduto;
import util.FormDatas;

/**
 *
 * @author benjamim
 */
public class ViewProdutos extends javax.swing.JFrame {
    ControllerFornecedor controllerF = new ControllerFornecedor();
    ControllerCategoria controllerC = new ControllerCategoria();
    ControllerProduto controllerP = new ControllerProduto();
    ArrayList<ModelFornecedor> listaF = new ArrayList<>();
    ArrayList<ModelCategoria> listaC = new ArrayList<>();
    ArrayList<ModelProduto> listaP = new ArrayList<>();
    ModelFornecedor modelF = new ModelFornecedor();
    ModelCategoria modelC = new ModelCategoria();
    ModelProduto modelP = new ModelProduto();
    FormDatas datas = new FormDatas();
    private int cont = 0;
    

    /**
     * Creates new form ViewProdutos
     */
    public ViewProdutos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        iniciarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtStockProdutos = new javax.swing.JTable();
        jbAlterar = new javax.swing.JButton();
        jbCancelar1 = new javax.swing.JButton();
        jbNova1 = new javax.swing.JButton();
        jbSalvar1 = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jtfPesquisar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcbFornecedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtfProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jsQuantidade = new javax.swing.JSpinner();
        jbCancelar = new javax.swing.JButton();
        jbNova = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jdcValidade = new com.toedter.calendar.JDateChooser();
        jtfCategoria = new javax.swing.JTextField();
        jbAdicionarCategoria = new javax.swing.JButton();
        jtfCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbValidavel = new javax.swing.JCheckBox();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jtStockProdutos.setAutoCreateRowSorter(true);
        jtStockProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Fornecedor", "Preco", "Disponivel", "validade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtStockProdutos);

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbCancelar1.setText("Cancelar");

        jbNova1.setText("Nova");

        jbSalvar1.setText("Salvar");
        jbSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvar1ActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyTyped(evt);
            }
        });

        jLabel8.setText("Pesquisar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbCancelar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNova1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCancelar1)
                            .addComponent(jbNova1))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Lista de produtos", jPanel3);

        jPanel2.setBackground(new java.awt.Color(130, 183, 235));

        jLabel4.setText("Fornecedor");

        jLabel5.setText("Categoria");

        jLabel6.setText("Produto");

        jtfProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfProdutoKeyTyped(evt);
            }
        });

        jLabel7.setText("Validade");

        jLabel1.setText("Preco");

        jtfPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecoKeyTyped(evt);
            }
        });

        jLabel2.setText("Quantidade");

        jsQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsQuantidadeStateChanged(evt);
            }
        });
        jsQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsQuantidadeMouseClicked(evt);
            }
        });
        jsQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jsQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jsQuantidadeKeyTyped(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");

        jbNova.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jbNova.setText("Nova");

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAdicionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jbAdicionarCategoria.setText("Adicionar");
        jbAdicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarCategoriaActionPerformed(evt);
            }
        });

        jtfCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCompraKeyTyped(evt);
            }
        });

        jLabel3.setText("Compra");

        jcbValidavel.setText("Com validade");
        jcbValidavel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jcbValidavelStateChanged(evt);
            }
        });
        jcbValidavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbValidavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbAdicionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jsQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jtfCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbNova, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jcbValidavel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jcbValidavel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbNova)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        jTabbedPane1.addTab("Adicionar Produtos", jPanel2);

        jToolBar1.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/house.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvar1ActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        
        if(JOptionPane.showInternalConfirmDialog(null, "Apagar?")==0){
          controllerP.excluirProdutoController((int) jtStockProdutos.getValueAt(jtStockProdutos.getSelectedRow(), 0));  
          preencherStock();
        } else{
            preencherStock();
        }
        
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
       preencherStockPesquisa();
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jtfPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyTyped
        preencherStockPesquisa();
    }//GEN-LAST:event_jtfPesquisarKeyTyped
    
    /**
     * Salva produtos
     * @param evt 
     */
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        try {
            modelP = new ModelProduto();
            
            if(jcbValidavel.isSelected()){
                modelP.setValidade(datas.converterDataParaDateUS(jdcValidade.getDate()));
            } else{
                modelP.setValidade(null);
            }
            modelP.setDataEntrega(datas.converterDataParaDateUS(new java.sql.Date(System.currentTimeMillis())));
            modelC = controllerC.getCategoria(String.valueOf(jcbCategoria.getSelectedItem()));
            modelP.setIdCategoria(modelC.getIdCategoria());
            modelF = controllerF.getFornecedorController(String.valueOf(jcbFornecedor.getSelectedItem()));

            modelP.setIdFornecedor(modelF.getIdFornecedor());
            modelP.setNomeProduto(jtfProduto.getText());
            modelP.setCompraProduto(Double.parseDouble(String.valueOf(jtfCompra.getText())));
            modelP.setPrecoProduto(Double.parseDouble(String.valueOf(jtfPreco.getText())));
            modelP.setStock(Integer.parseInt(String.valueOf(jsQuantidade.getValue())));
            

            if( controllerP.salvarProdutoController(modelP)>0){
                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
            } else{
                JOptionPane.showMessageDialog(null, "Problemas ao salvar");
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewProdutos.class.getName()).log(Level.SEVERE, null, ex);

        }
        iniciarCampos();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtfProdutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProdutoKeyTyped
       char c = evt.getKeyChar();
        
        if((c<'a'||c>'z') && (c<'A'|| c>'Z') && (c!=' ') )
           evt.consume();
    }//GEN-LAST:event_jtfProdutoKeyTyped

    private void jtfPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecoKeyTyped
        char c = evt.getKeyChar();
        
        if((c<'0'||c>'9') )
           evt.consume();
    }//GEN-LAST:event_jtfPrecoKeyTyped

    private void jsQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsQuantidadeKeyTyped
        char c = evt.getKeyChar();
        
        if((c<'0'||c>'9') )
           evt.consume();
    }//GEN-LAST:event_jsQuantidadeKeyTyped

    private void jbAdicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarCategoriaActionPerformed
       if(!String.valueOf(jtfCategoria.getText()).equals("")){
        modelC.setNomeCategoria(String.valueOf(jtfCategoria.getText()));
        
        controllerC.salvarCategoria(modelC);
        jtfCategoria.setText("");
        preencherCategoria();
    } else{
            JOptionPane.showMessageDialog(null, "Sem categoria por adicionar");
            }
        
    }//GEN-LAST:event_jbAdicionarCategoriaActionPerformed

    private void jsQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsQuantidadeKeyReleased
    }//GEN-LAST:event_jsQuantidadeKeyReleased

    private void jsQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsQuantidadeStateChanged
    }//GEN-LAST:event_jsQuantidadeStateChanged

    private void jsQuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsQuantidadeMouseClicked
        
        
    }//GEN-LAST:event_jsQuantidadeMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new ViewPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtfCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompraKeyTyped

    private void jcbValidavelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jcbValidavelStateChanged
       if(jcbValidavel.isSelected()){
          jdcValidade.setEnabled(true); 
       } else{
           jdcValidade.setEnabled(false); 
       }
    }//GEN-LAST:event_jcbValidavelStateChanged

    private void jcbValidavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbValidavelActionPerformed
         
    }//GEN-LAST:event_jcbValidavelActionPerformed

    private void preencherProdutos(){
        DefaultTableModel modelo = (DefaultTableModel) jtStockProdutos.getModel();
        
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProdutos().setVisible(true);
            }
        });
    }
    
    private void iniciarCampos(){
        preencherFornecedor();
        preencherCategoria();
        preencherStock();
        jtfProduto.setText("");
        jtfPreco.setText("");
        jtfCompra.setText("");
        jdcValidade.setDate(null);
        jdcValidade.setEnabled(false);
        jsQuantidade.setValue(0);
        
    }
    
    private void preencherFornecedor(){
        jcbFornecedor.removeAllItems();
        listaF = controllerF.getListaFornecedorController();
        
        for(int i=0; i<listaF.size(); i++){
            jcbFornecedor.addItem(listaF.get(i).getNomeFornecedor());
        }
        jcbFornecedor.setSelectedIndex(-1);
    }
    
    private void preencherCategoria(){
        jcbCategoria.removeAllItems();
        listaC = controllerC.getListaCategoria();
        
        for(int i=0; i<listaC.size(); i++){
            jcbCategoria.addItem(listaC.get(i).getNomeCategoria());
        }
        jcbCategoria.setSelectedIndex(-1);
    }
    
    private void preencherStock(){
        listaP = controllerP.getListaProdutoController();
        
        DefaultTableModel modelo = (DefaultTableModel) jtStockProdutos.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<listaP.size(); i++){
            modelF = controllerF.getFornecedorController(listaP.get(i).getIdFornecedor());
            
            modelo.addRow(new Object[]{
            listaP.get(i).getIdProduto(),
            listaP.get(i).getNomeProduto(),
            modelF.getNomeFornecedor(),
            listaP.get(i).getPrecoProduto(),
            listaP.get(i).getStock(),
            listaP.get(i).getValidade().toString()
            
            });
        }
        
        
    }
    private void preencherStockPesquisa(){
        listaP = controllerP.getListaProdutoController();
        
        DefaultTableModel modelo = (DefaultTableModel) jtStockProdutos.getModel();
        modelo.setNumRows(0);
        for(int i=0; i<listaP.size(); i++){
            
            modelF = controllerF.getFornecedorController(listaP.get(i).getIdFornecedor());
            
            if(listaP.get(i).getNomeProduto().contains(jtfPesquisar.getText())){
            modelo.addRow(new Object[]{
            listaP.get(i).getIdProduto(),
            listaP.get(i).getNomeProduto(),
            modelF.getNomeFornecedor(),
            listaP.get(i).getPrecoProduto(),
            listaP.get(i).getStock(),
            listaP.get(i).getValidade().toString()
            }); 
            }
            
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbAdicionarCategoria;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelar1;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNova;
    private javax.swing.JButton jbNova1;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvar1;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbFornecedor;
    private javax.swing.JCheckBox jcbValidavel;
    private com.toedter.calendar.JDateChooser jdcValidade;
    private javax.swing.JSpinner jsQuantidade;
    private javax.swing.JTable jtStockProdutos;
    private javax.swing.JTextField jtfCategoria;
    private javax.swing.JTextField jtfCompra;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JTextField jtfProduto;
    // End of variables declaration//GEN-END:variables
}
