/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerProduto;
import controller.ControllerCategoria;
import controller.ControllerCategoriaProduto;
import controller.ControllerFornecedor;
import controller.ControllerVenda;
import controller.ControllerVendaCliente;
import controller.ControllerVendasProdutos;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCategoria;
import model.ModelCategoriaProduto;
import model.ModelCliente;
import model.ModelFornecedor;
import model.ModelProduto;
import model.ModelVenda;
import model.ModelVendaCliente;
import model.ModelVendasProdutos;
import util.FormDatas;

/**
 *Tela para efectuar vendas e verificar as vendas efectuadas
 * @author benjamim
 */
public class ViewVendas extends javax.swing.JFrame {
    ModelFornecedor modelF = new ModelFornecedor();
    ControllerFornecedor controllerF = new ControllerFornecedor();
    
    ModelCategoria modelC = new ModelCategoria();
    ControllerCategoria controll = new ControllerCategoria();
    
     ArrayList<ModelVendasProdutos> listaVP = new ArrayList<>();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ControllerVendasProdutos controllerVP = new ControllerVendasProdutos();
    
    ModelProduto modelProduto = new ModelProduto();
    ControllerProduto controllerProduto = new ControllerProduto();
    ArrayList<ModelProduto> listaProdutos = new ArrayList<>();
    
    ModelCliente modelCliente = new ModelCliente();
    ControllerCliente controllerCliente = new ControllerCliente();
    ArrayList<ModelCliente> listaCliente = new ArrayList<>();
    
    ArrayList<ModelVendaCliente> listaVendaCliente = new ArrayList<>();
    ModelVendaCliente modelVendaCliente = new ModelVendaCliente();
    ControllerVendaCliente controllerVendaCliente = new ControllerVendaCliente();
    
    ModelVenda modelVenda = new ModelVenda();
    ControllerVenda controllerVenda = new ControllerVenda();
    
    ModelCategoriaProduto modelCP = new ModelCategoriaProduto();
    ControllerCategoriaProduto controllerCP = new ControllerCategoriaProduto();
    
    FormDatas datas = new FormDatas();    
    private double total = 0;
    private int codigoVenda = 0;

    /**
     * Creates new form ViewVendas
     */
    public ViewVendas() {
        initComponents();
        preencherCampos();
        carregarVendas();
        preencherProdutos();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        aluminiumDefaultTheme1 = new com.jtattoo.plaf.aluminium.AluminiumDefaultTheme();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigoCliente = new javax.swing.JTextField();
        jcbCliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jsQuantidade = new javax.swing.JSpinner();
        jbAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVenda = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jbRemover = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtfPreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfDesconto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfTotal = new javax.swing.JTextField();
        jbFinalizar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jcbPagamento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jtfRecebido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfTrocos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendaCliente = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel2.setText("Cliente");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jtfCodigoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoClienteKeyReleased(evt);
            }
        });
        jPanel2.add(jtfCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 49, -1));

        jcbCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jcbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jcbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 330, -1));

        jLabel5.setText("Quantidade");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));
        jPanel2.add(jsQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 90, -1));

        jbAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket_put.png"))); // NOI18N
        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });
        jPanel2.add(jbAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 120, 40));

        jtVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Quant.", "Preco u.", "A pagar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtVenda);
        if (jtVenda.getColumnModel().getColumnCount() > 0) {
            jtVenda.getColumnModel().getColumn(0).setMinWidth(80);
            jtVenda.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtVenda.getColumnModel().getColumn(0).setMaxWidth(80);
            jtVenda.getColumnModel().getColumn(2).setMinWidth(80);
            jtVenda.getColumnModel().getColumn(2).setPreferredWidth(80);
            jtVenda.getColumnModel().getColumn(2).setMaxWidth(80);
            jtVenda.getColumnModel().getColumn(3).setMinWidth(80);
            jtVenda.getColumnModel().getColumn(3).setPreferredWidth(80);
            jtVenda.getColumnModel().getColumn(3).setMaxWidth(80);
            jtVenda.getColumnModel().getColumn(4).setMinWidth(80);
            jtVenda.getColumnModel().getColumn(4).setPreferredWidth(80);
            jtVenda.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 740, 179));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 110, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket_add.png"))); // NOI18N
        jButton2.setText("Nova");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 100, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 76, 30, 20));

        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });
        jPanel2.add(jtfPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 220, 30));

        jbRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket_remove.png"))); // NOI18N
        jbRemover.setText("Remover");
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });
        jPanel2.add(jbRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, -1, 30));

        jPanel3.setBackground(new java.awt.Color(158, 165, 151));

        jLabel10.setText("Preco");

        jtfPreco.setEditable(false);

        jLabel6.setText("Desconto");

        jtfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDescontoKeyReleased(evt);
            }
        });

        jLabel7.setBackground(java.awt.Color.black);
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Total");
        jLabel7.setEnabled(false);

        jtfTotal.setEditable(false);
        jtfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTotalActionPerformed(evt);
            }
        });

        jbFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket_go.png"))); // NOI18N
        jbFinalizar.setText("Finalizar");
        jbFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarActionPerformed(evt);
            }
        });

        jLabel11.setText("Forma de pagamento");

        jcbPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A vista", "Credito", "Debito" }));
        jcbPagamento.setSelectedIndex(-1);
        jcbPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPagamentoActionPerformed(evt);
            }
        });

        jLabel12.setText("Recebido");

        jtfRecebido.setEditable(false);
        jtfRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfRecebidoKeyReleased(evt);
            }
        });

        jLabel13.setText("Trocos");

        jtfTrocos.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(jtfTotal)
                                .addComponent(jtfDesconto))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jtfTrocos)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jbFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jcbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfTrocos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jbFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 370, 540));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 80, -1));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/basket.png"))); // NOI18N
        jLabel15.setText("Carrinha");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 298, 90, 30));

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Fornecedor", "Stock", "Preco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtProdutos);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 740, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/database.png"))); // NOI18N
        jLabel3.setText("Produtos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, -1));

        jTabbedPane1.addTab("Caixa", jPanel2);

        jtVendaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID venda", "Nome  do Cliente", "Valor da venda", "Data da Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtVendaCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de vendas", jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/house.png"))); // NOI18N
        jMenu3.setText("Menu principal");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu3.add(jSeparator1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRecebidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfRecebidoKeyReleased
        double recebido=0;
        double total=0;
        try{

            total = Double.parseDouble(String.valueOf(jtfTotal.getText()));
            recebido = Double.parseDouble(String.valueOf(jtfRecebido.getText()));
        } catch(NumberFormatException e){
            recebido = 0;
        }

        if(recebido>=total)
        jtfTrocos.setText(String.valueOf(recebido-total));
    }//GEN-LAST:event_jtfRecebidoKeyReleased

    private void jcbPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPagamentoActionPerformed
        if(jcbPagamento.getSelectedIndex()==0){
            jtfRecebido.setEditable(true);
        }
    }//GEN-LAST:event_jcbPagamentoActionPerformed

    private void jbFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarActionPerformed
        modelVenda = new ModelVenda();

        try {
            modelVenda.setDataVenda(datas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
                ex.printStackTrace();
        }
        try{
            modelVenda.setDescontoVenda(Double.parseDouble(String.valueOf(jtfDesconto.getText())));
        } catch(NumberFormatException e){
            modelVenda.setDescontoVenda(0);
        }

        modelVenda.setIdCliente(Integer.parseInt(String.valueOf(jtfCodigoCliente.getText())));
        modelVenda.setValorVenda(Double.parseDouble(String.valueOf(jtfPreco.getText())));
        modelVenda.setTotalVenda(Double.parseDouble(String.valueOf(jtfTotal.getText())));

        codigoVenda = controllerVenda.salvarVendaController(modelVenda);
        if(codigoVenda > 0){
            JOptionPane.showMessageDialog(null, "Venda sucedida");
            total=0;
        } else{
            JOptionPane.showMessageDialog(null, "Erro ao vender");
        }

        int cont = jtVenda.getRowCount();
        for(int i=0; i<cont; i++){
            modelVendasProdutos = new ModelVendasProdutos();
            modelVendasProdutos.setProduto((int) jtVenda.getValueAt(i, 0));
            modelVendasProdutos.setVenda(codigoVenda);
            modelVendasProdutos.setQuantidadeVenda((int) jtVenda.getValueAt(i, 2));
            modelVendasProdutos.setValorVenda((double) jtVenda.getValueAt(i, 4));

            listaVP.add(modelVendasProdutos);
        }
        if( controllerVP.salvarVendasProdutosController(listaVP)){
            for(int i=0; i<cont; i++){
                int pos = Integer.parseInt(String.valueOf(jtVenda.getValueAt(i, 0)));
                int quant = Integer.parseInt(String.valueOf(jtVenda.getValueAt(i, 2)));
                modelProduto = controllerProduto.getProdutoController(pos);
                modelProduto.setStock(modelProduto.getStock()-quant);
                if(modelProduto.getStock()==0){
                    controllerProduto.excluirProdutoController(modelProduto.getIdProduto());
                } else{
                     controllerProduto.atualizarProdutoQuantidade(modelProduto, pos);
                }
            }
        }
        preencherProdutos();
         limparCampos();
            carregarVendas();
    }//GEN-LAST:event_jbFinalizarActionPerformed

    private void jtfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTotalActionPerformed

    private void jtfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescontoKeyReleased
        double desconto=0;

        try{
            desconto = Double.parseDouble(String.valueOf(getJtfDesconto().getText()));
        } catch(NumberFormatException e){
            desconto=0;
        }

        if(desconto<total){

            jtfTotal.setText(String.valueOf(total - desconto));

        } else{
            JOptionPane.showInternalMessageDialog(null, "Desconto acima do valor. ", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jtfDescontoKeyReleased

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jtVenda.getModel();
        modelo.removeRow(jtVenda.getSelectedRow());

        total+= Double.parseDouble(String.valueOf(jsQuantidade.getValue()))*modelProduto.getPrecoProduto();
        jtfPreco.setText(String.valueOf(total));
        jtfTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jtVenda.getModel();
        if(jtProdutos.getSelectedRow()!=-1){
            modelProduto = controllerProduto.getProdutoController((int) jtProdutos.getValueAt(jtProdutos.getSelectedRow(), 0));
        } else{
            JOptionPane.showInternalMessageDialog(null, "Selecione o produto", "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
        }
        

        if(Integer.parseInt(String.valueOf( jsQuantidade.getValue()))> modelProduto.getStock()){
            JOptionPane.showInternalMessageDialog(null, "Quantidade nao disponivel", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else{
            modelo.addRow(new Object[]{
                modelProduto.getIdProduto(),
                modelProduto.getNomeProduto(),
                jsQuantidade.getValue(),
                modelProduto.getPrecoProduto(),
                Double.parseDouble(String.valueOf(jsQuantidade.getValue()))*modelProduto.getPrecoProduto()
            });

            total+= Double.parseDouble(String.valueOf(jsQuantidade.getValue()))*modelProduto.getPrecoProduto();
            jtfPreco.setText(String.valueOf(total));
            jtfTotal.setText(String.valueOf(total));

        }

    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jcbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbClienteActionPerformed

    private void jcbClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbClientePopupMenuWillBecomeInvisible
        if(jcbCliente.getSelectedIndex()!=-1){
            modelCliente = controllerCliente.getClienteController(jcbCliente.getSelectedItem().toString());
            jtfCodigoCliente.setText(String.valueOf(modelCliente.getIdCliente()));
        }
    }//GEN-LAST:event_jcbClientePopupMenuWillBecomeInvisible

    private void jtfCodigoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoClienteKeyReleased
        modelCliente = controllerCliente.getClienteController(Integer.parseInt(jtfCodigoCliente.getText()));

        jcbCliente.setSelectedItem(modelCliente.getNomeCliente());
    }//GEN-LAST:event_jtfCodigoClienteKeyReleased

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        new ViewCaixa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new ViewAdicionarCliente().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        listaProdutos = controllerProduto.getListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) jtProdutos.getModel();
        modelo.setNumRows(0);
        
        for(int i=0; i<listaProdutos.size(); i++){
            if(listaProdutos.get(i).getNomeProduto().contains(String.valueOf(jtfPesquisar.getText()))){
               modelo.addRow(new Object[]{
            listaProdutos.get(i).getIdProduto(),
            listaProdutos.get(i).getNomeProduto(),
            modelF.getNomeFornecedor(),
            listaProdutos.get(i).getStock(),
            listaProdutos.get(i).getPrecoProduto()
            }); 
            }
        }
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }
    
    private void preencherCampos(){
        preencherCliente();
       
        limparCampos();
        jtfTotal.setEditable(false);
        
        
    }
    
    /**
     * Limpa os campos de edicao
     */
    private void limparCampos(){
        jtfCodigoCliente.setText("");
        jcbCliente.setSelectedIndex(-1);
        jsQuantidade.setValue(0);
        jtfPreco.setText("");
        jtfDesconto.setText("");
        jtfTotal.setText("");
        jtfRecebido.setText("");
        jtfTrocos.setText("");
        
        
        DefaultTableModel modelo = (DefaultTableModel) jtVenda.getModel();
        modelo.setNumRows(0);
        
    }
     private void preencherCliente(){
        listaCliente = controllerCliente.getListaClienteController();
        jcbCliente.removeAllItems();
        for (int i=0; i<listaCliente.size(); i++){
            
            jcbCliente.addItem(listaCliente.get(i).getNomeCliente());
        }
        
    }
     
    
     
      public void carregarVendas(){
        DefaultTableModel modelo = (DefaultTableModel) jtVendaCliente.getModel();
        listaVendaCliente = controllerVendaCliente.getListaVendaCliente();
        modelo.setNumRows(0);
        int cont = listaVendaCliente.size();
        for(int i=0; i<cont; i++){
            modelo.addRow(new Object[]{
            listaVendaCliente.get(i).getModelVenda().getIdVenda(),
            listaVendaCliente.get(i).getModelCliente().getNomeCliente(),
            listaVendaCliente.get(i).getModelVenda().getValorVenda(),
            listaVendaCliente.get(i).getModelVenda().getDataVenda().toString()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jtattoo.plaf.aluminium.AluminiumDefaultTheme aluminiumDefaultTheme1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbFinalizar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JComboBox<String> jcbCliente;
    private javax.swing.JComboBox<String> jcbPagamento;
    private javax.swing.JSpinner jsQuantidade;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTable jtVenda;
    private javax.swing.JTable jtVendaCliente;
    private javax.swing.JTextField jtfCodigoCliente;
    private javax.swing.JTextField jtfDesconto;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfPreco;
    private javax.swing.JTextField jtfRecebido;
    private javax.swing.JTextField jtfTotal;
    private javax.swing.JTextField jtfTrocos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jtfDesconto
     */
    public javax.swing.JTextField getJtfDesconto() {
        return jtfDesconto;
    }

    private void preencherProdutos() {
        listaProdutos = controllerProduto.getListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) jtProdutos.getModel();
        
        modelo.setNumRows(0);
        
        for(int i=0; i<listaProdutos.size(); i++){
            modelF = controllerF.getFornecedorController(listaProdutos.get(i).getIdFornecedor());
            modelo.addRow(new Object[]{
            listaProdutos.get(i).getIdProduto(),
            listaProdutos.get(i).getNomeProduto(),
            modelF.getNomeFornecedor(),
            listaProdutos.get(i).getStock(),
            listaProdutos.get(i).getPrecoProduto()
            });
            
        }
        
        
    }

   
}
